export const QUOTES_DB = {
  motivation: [
    "The only way to do great work is to love what you do.",
    "Believe you can and you're halfway there.",
    "Don't watch the clock; do what it does. Keep going.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn’t just find you. You have to go out and get it.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don’t stop when you’re tired. Stop when you’re done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little things make big days.",
    "It’s going to be hard, but hard does not mean impossible.",
    "Don’t wait for opportunity. Create it.",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.",
    "The key to success is to focus on goals, not obstacles.",
    "Dream it. Believe it. Build it.",
    "Act as if what you do makes a difference. It does.",
    "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "Never bend your head. Always hold it high. Look the world straight in the eye.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "It is during our darkest moments that we must focus to see the light.",
    "Limit your 'always' and your 'nevers.'",
    "Nothing is impossible. The word itself says 'I'm possible!'",
    "You do not find the happy life. You make it.",
    "Stay close to anything that makes you glad you are alive.",
    "Make each day your masterpiece.",
    "Happiness is not by chance, but by choice.",
    "You must do the things you think you cannot do.",
    "The power of imagination makes us infinite.",
    "Try to be a rainbow in someone else's cloud.",
    "Keep your face always toward the sunshine, and shadows will fall behind you.",
    "You are never too old to set another goal or to dream a new dream.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "We can do anything we want to if we stick to it long enough.",
    "Believe and act as if it were impossible to fail.",
    "Start where you are. Use what you have. Do what you can.",
    "Expect problems and eat them for breakfast.",
    "The best way to predict the future is to create it.",
    "Opportunities don't happen, you create them.",
    "It always seems impossible until it's done.",
    "Your passion is waiting for your courage to catch up.",
    "If you want to fly, give up everything that weighs you down.",
    "Do what you can, with what you have, where you are.",
    "The secret of getting ahead is getting started.",
    "Quality is not an act, it is a habit.",
    "Well begun is half done.",
    "Go confidently in the direction of your dreams.",
    "Action is the foundational key to all success.",
    "Do not let what you cannot do interfere with what you can do.",
    "The path to success is to take massive, focused action.",
    "If opportunity doesn't knock, build a door.",
    "We generate fears while we sit. We overcome them by action.",
    "Today's accomplishments were yesterday's impossibilities.",
    "Do not wait; the time will never be 'just right.'",
    "Press forward. Do not stop, do not linger in your journey.",
    "The most effective way to do it, is to do it.",
    "An obstacle is often a stepping stone.",
    "Hard work beats talent when talent doesn't work hard.",
    "No pressure, no diamonds.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "It is never too late to be what you might have been.",
    "Everything you've ever wanted is on the other side of fear.",
    "You miss 100% of the shots you don't take.",
    "Failure is simply the opportunity to begin again, this time more intelligently.",
    "If you can dream it, you can do it.",
    "Don't limit your challenges. Challenge your limits.",
    "The only true limit is the one you set yourself.",
    "Change your thoughts and you change your world.",
    "There is no failure except in no longer trying.",
    "Fall seven times, stand up eight.",
    "Focus on progress, not perfection.",
    "Great works are performed not by strength but by perseverance.",
    "Energy and persistence conquer all things.",
    "You are stronger than you think.",
    "Small progress is still progress.",
    "Make today so awesome yesterday gets jealous.",
    "Be the change that you wish to see in the world.",
    "Nothing worth having comes easy.",
    "Never give up on a dream just because of the time it will take to accomplish it.",
    "Live, love, laugh, learn.",
    "Work hard in silence, let your success be your noise.",
    "You don't have to be great to start, but you have to start to be great.",
    "Do it with passion or not at all.",
    "Believe in the power of yet.",
    "Difficult roads often lead to beautiful destinations.",
    "The best view comes after the hardest climb.",
    "Make your life a story worth telling.",
    "Be yourself; everyone else is already taken.",
    "The mindset is everything.",
    "Be a voice, not an echo.",
    "Every day is a second chance.",
    "Do what you love, love what you do.",
    "Make your dreams happen.",
    "Invest in your dreams. Grind now. Shine later.",
    "One day or day one. You decide.",
    "Your life does not get better by chance, it gets better by change.",
    "Hustle until your haters ask if you're hiring.",
    "Success is a series of small wins.",
    "You are capable of amazing things.",
    "Great things take time."
  ],
  success: [
    "Success is not final; failure is not fatal: it is the courage to continue that counts.",
    "Play by the rules, but be ferocious.",
    "Business opportunities are like buses, there's always another one coming.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The way to get started is to quit talking and begin doing.",
    "If you really look closely, most overnight successes took a long time.",
    "The secret of success is to do the common thing uncommonly well.",
    "I find that the harder I work, the more luck I seem to have.",
    "Opportunities don't happen. You create them.",
    "Successful people do what unsuccessful people are not willing to do.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "The starting point of all achievement is desire.",
    "Everything you've ever wanted is on the other side of fear.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "What seems to us as bitter trials are often blessings in disguise.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Don't be afraid to give up the good to go for the great.",
    "I never dreamed about success, I worked for it.",
    "Success is how high you bounce when you hit bottom.",
    "Action is the foundational key to all success.",
    "To succeed in life, you need two things: ignorance and confidence.",
    "I owe my success to having listened respectfully to the very best advice, and then going away and doing the exact opposite.",
    "The key to success is to focus on goals, not obstacles.",
    "Success is not in what you have, but who you are.",
    "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "Success is simple. Do what's right, the right way, at the right time.",
    "In order to succeed, we must first believe that we can.",
    "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.",
    "The path to success is to take massive, focused action.",
    "Put your heart, mind, and soul into even your smallest acts. This is the secret of success.",
    "The secret of success in every venture is to know how to handle the human element.",
    "The only place where success comes before work is in the dictionary.",
    "To achieve great things, two things are needed: a plan and not quite enough time.",
    "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.",
    "The distance between insanity and genius is measured only by success.",
    "Always bear in mind that your own resolution to succeed is more important than any other.",
    "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.",
    "Patience, persistence, and perspiration make an unbeatable combination for success.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "The ones who are crazy enough to think they can change the world are the ones that do.",
    "All progress takes place outside the comfort zone.",
    "The starting point of all achievement is desire. Keep this constantly in mind.",
    "He who has a why to live can bear almost any how.",
    "Success is not just about what you accomplish in your life, it's about what you inspire others to do.",
    "Small daily improvements over time lead to stunning results.",
    "The true measure of success is how many times you can bounce back from failure.",
    "Make your life a masterpiece; imagine no limitations on what you can be, have or do.",
    "It is hard to fail, but it is worse never to have tried to succeed.",
    "Do not aim for success if you want it; just do what you love and believe in, and it will come naturally.",
    "The level of our success is limited only by our imagination and no act of kindness, however small, is ever wasted.",
    "Success is where preparation and opportunity meet.",
    "Choose a job you love, and you will never have to work a day in your life.",
    "If you don't build your dream, someone else will hire you to help them build theirs.",
    "If you want to make your dreams come true, the first thing you have to do is wake up.",
    "Genius is 1% inspiration, 99% perspiration.",
    "Success is the progressive realization of a worthy ideal.",
    "If you do what you've always done, you'll get what you've always gotten.",
    "Failure is the condiment that gives success its flavor.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "A year from now you may wish you had started today.",
    "Keep your eyes on the stars, and your feet on the ground.",
    "A journey of a thousand miles begins with a single step.",
    "Winners never quit and quitters never win.",
    "Don't worry about failures, worry about the chances you miss when you don't even try.",
    "Believe in yourself! Have faith in your abilities!",
    "Success comes from having the courage to begin.",
    "Nothing succeeds like success.",
    "Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.",
    "It is your attitude, not your aptitude, that determines your altitude.",
    "Your success and happiness lie in you.",
    "The secret of success is constancy to purpose.",
    "Be ferocious in the pursuit of what sets your soul on fire.",
    "Hard work makes the dreams work.",
    "Never compromise on your vision.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Focus on your goals and blur the noise.",
    "Make success your only option.",
    "You are built to last and engineered to win.",
    "Work hard, stay humble, dream big.",
    "Rise above the storm and you will find the sunshine.",
    "Success belongs to those who prepare for it today.",
    "There are no shortcuts to any place worth going.",
    "Keep pushing, your breakthrough is near.",
    "Consistency is the key that unlocks the door to success.",
    "Dream big, work hard, stay focused, and surround yourself with good people.",
    "Do it with passion or not at all.",
    "Make your effort count.",
    "Every expert was once a beginner.",
    "The best revenge is massive success.",
    "Live your life by design, not by default.",
    "Doubt kills more dreams than failure ever will.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Your future is created by what you do today, not tomorrow.",
    "Go the extra mile. It's never crowded there.",
    "Do what is right, not what is easy.",
    "Believing in yourself is the first secret of success.",
    "Keep grinding. Your time is coming."
  ],
  love: [
    "To love and be loved is to feel the sun from both sides.",
    "The best thing to hold onto in life is each other.",
    "You are my today and all of my tomorrows.",
    "Love is not about how many days, months, or years you have been together.",
    "Where there is love there is life.",
    "If I know what love is, it is because of you.",
    "My soul and your soul are forever tangled.",
    "Love all, trust a few, do wrong to none.",
    "Life without love is like a tree without blossoms or fruit.",
    "The greatest healing therapy is friendship and love.",
    "Love is when the other person's happiness is more important than your own.",
    "You don't marry someone you can live with—you marry someone you cannot live without.",
    "In all the world, there is no heart for me like yours.",
    "I saw that you were perfect, and so I loved you.",
    "Being deeply loved by someone gives you strength.",
    "There is only one happiness in this life, to love and be loved.",
    "Love is a canvas furnished by nature and embroidered by imagination.",
    "We love because it's the only true adventure.",
    "To the world you may be one person, but to one person you are the world.",
    "Love is composed of a single soul inhabiting two bodies.",
    "We are most alive when we're in love.",
    "All you need is love. But a little chocolate now and then doesn't hurt.",
    "The art of love is largely the art of persistence.",
    "If you would be loved, love and be lovable.",
    "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
    "Kindness in words creates confidence. Kindness in thinking creates profoundness. Kindness in giving creates love.",
    "We love the things we love for what they are.",
    "A loving heart is the truest wisdom.",
    "Love is the beauty of the soul.",
    "True love stories never have endings.",
    "Love is a friendship set to music.",
    "There is no remedy for love but to love more.",
    "In love, one and one are one.",
    "You are my heart, my life, my entire existence.",
    "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination.",
    "A simple 'I love you' means more than money.",
    "If I had a flower for every time I thought of you... I could walk through my garden forever.",
    "The water shines only by the sun. And it is you who are my sun.",
    "To love is to burn, to be on fire.",
    "I love you not only for what you are, but for what I am when I am with you.",
    "Love is the ultimate outlaw. It just won't adhere to any rules.",
    "Grow old along with me! The best is yet to be.",
    "You make my heart smile.",
    "Every time I see you, I fall in love all over again.",
    "Your voice is my favorite sound.",
    "Where there is great love, there are always miracles.",
    "Love is the light that guides us through the darkest times.",
    "I love you more than words can describe.",
    "You are the peace in my chaotic world.",
    "I want to be your favorite hello and your hardest goodbye.",
    "Together is my favorite place to be.",
    "Your love is all I need to feel complete.",
    "You are my anchor when the waves roll in.",
    "You are my absolute favorite person in the universe.",
    "My heart is and always will be yours.",
    "To be your friend was all I ever wanted; to be your lover was all I ever dreamed.",
    "When I look into your eyes, I see the mirror of my soul.",
    "No matter what has happened, no matter what you have done, I will always love you.",
    "Love is a promise; love is a souvenir, once given never forgotten.",
    "You are the poem I never knew how to write.",
    "I love you from the bottom of my heart.",
    "Two hearts, one heartbeat.",
    "I choose you. And I'll choose you over and over.",
    "You are my home, and I love coming home.",
    "In a sea of people, my eyes will always search for you.",
    "You are my sunshine on a rainy day.",
    "Every love story is beautiful, but ours is my favorite.",
    "I loved you yesterday, love you still, always have, always will.",
    "Love is not finding someone to live with; it's finding someone you can't live without.",
    "You make me want to be a better person.",
    "My favorite place in all the world is next to you.",
    "You are the best thing that's ever been mine.",
    "I am yours, completely and forever.",
    "Your smile is the light of my life.",
    "We belong together, like peanut butter and jelly.",
    "In your arms, I am safe, I am warm, I am home.",
    "Love is a master key that opens the gates of happiness.",
    "You are the icing on my cake.",
    "Love is life. And if you miss love, you miss life.",
    "You hold the key to my heart.",
    "My love for you is a journey, starting at forever and ending at never.",
    "I find pieces of you in every song I listen to.",
    "You are my spark in the dark.",
    "Love is the thread that binds us together.",
    "You have my whole heart for my whole life.",
    "I love you to the moon and back.",
    "You are my cup of tea.",
    "Loving you is as natural as breathing.",
    "Your hug makes everything better.",
    "With you, time stands still.",
    "You are the sweet to my sour.",
    "No measure of time with you will be long enough.",
    "You are my happy place.",
    "My love for you grows stronger day by day.",
    "You are the reason my heart beats.",
    "Every day spent with you is my favorite day.",
    "You are the dream I never want to wake up from.",
    "Loving you is my favorite adventure.",
    "You are the perfect puzzle piece to my heart.",
    "Forever is a long time, but I want to spend it with you."
  ],
  life: [
    "Life is what happens when you're busy making other plans.",
    "Get busy living or get busy dying.",
    "You only live once, but if you do it right, once is enough.",
    "The purpose of our lives is to be happy.",
    "Life is a long lesson in humility.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "Life is really simple, but we insist on making it complicated.",
    "The unexamined life is not worth living.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Your time is limited, so don't waste it living someone else's life.",
    "Good friends, good books, and a sleepy conscience: this is the ideal life.",
    "Life is either a daring adventure or nothing at all.",
    "Keep smiling, because life is a beautiful thing.",
    "Life is made of ever so many partings welded together.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The way I see it, if you want the rainbow, you gotta put up with the rain.",
    "Life is short, and it is here to be lived.",
    "Turn your wounds into wisdom.",
    "Life isn't about finding yourself. Life is about creating yourself.",
    "Live in the sunshine, swim the sea, drink the wild air.",
    "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.",
    "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.",
    "To live is the rarest thing in the world. Most people exist, that is all.",
    "The standard of life is measured by the quality of our relationships.",
    "Life is like riding a bicycle. To keep your balance, you must keep moving.",
    "Life is a succession of lessons which must be lived to be understood.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    "The only impossible journey is the one you never begin.",
    "Life is not a problem to be solved, but a reality to be experienced.",
    "Go confidently in the direction of your dreams! Live the life you've imagined.",
    "Change is the law of life. And those who look only to the past or present are certain to miss the future.",
    "Only a life lived for others is a life worthwhile.",
    "Do not let making a living prevent you from making a life.",
    "Life is too short to waste on negative energy.",
    "Enjoy the little things in life, for one day you may look back and realize they were the big things.",
    "Be happy for this moment. This moment is your life.",
    "Life is a book, and those who do not travel read only a page.",
    "Every moment is a fresh beginning.",
    "The energy of the mind is the essence of life.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "Life is dynamic; change is the only constant.",
    "We do not remember days, we remember moments.",
    "Life is a progress, and not a station.",
    "The best portion of a good man's life is his little nameless, unremembered acts of kindness and love.",
    "Life is like a box of chocolates. You never know what you're gonna get.",
    "Difficulties strengthen the mind, as labor does the body.",
    "Life is short, spend it with people who make you laugh and feel loved.",
    "The secret of life is to appreciate the beauty around you.",
    "Write your own story.",
    "Embrace the glorious mess that you are.",
    "Make your life a canvas of colorful memories.",
    "Live each day as if it were your last, with passion and purpose.",
    "Life is a journey, not a destination.",
    "Every day brings new choices.",
    "Life is a beautiful struggle.",
    "Make time for things that make you feel alive.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "Collect moments, not things.",
    "Live simply. Dream big. Be grateful. Give love.",
    "Life is a challenge, meet it.",
    "Open your mind to the endless possibilities of life.",
    "Life is 10% learning and 90% experiencing.",
    "Do not count the days, make the days count.",
    "Life is a wave, catch it.",
    "Live with intention and without regrets.",
    "Your life is your message to the world. Make it inspiring.",
    "Life is a puzzle; every piece fits eventually.",
    "Choose peace over drama in your life.",
    "Be kind to yourself; life is a learning curve.",
    "Fill your life with adventures, not excuses.",
    "Life is too short to be anything but happy.",
    "Your life is the result of your choices.",
    "Life is a song, sing it.",
    "The beauty of life is in its unpredictability.",
    "Live in the present moment, it is the only one we have.",
    "Keep moving forward, life doesn't wait.",
    "Life is what you make it. Always has been, always will be.",
    "Find joy in the ordinary.",
    "Life is a gift; cherish it.",
    "Live boldly and passionately.",
    "Life is too beautiful to be spent in anger or sadness.",
    "Your life is your art.",
    "Make your life a story worth telling.",
    "Trust the timing of your life.",
    "Every day is a fresh page in the book of your life.",
    "Enjoy the journey, not just the summit.",
    "Life is a mirror; it reflects what you project.",
    "Be present in all things.",
    "Life is full of blessings if you look closely.",
    "Make peace with your past so it won't spoil your present.",
    "Live the life you love, love the life you live.",
    "Your life is your masterpiece in progress.",
    "Make every day count.",
    "Life is short. Do what matters.",
    "Focus on the good in your life.",
    "Be the author of your own life.",
    "Life is a grand adventure."
  ],
  wisdom: [
    "The only true wisdom is in knowing you know nothing.",
    "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    "Silence is a source of great strength.",
    "Knowing yourself is the beginning of all wisdom.",
    "Count your age by friends, not years. Count your life by smiles, not tears.",
    "The journey of a thousand miles begins with one step.",
    "It is the mark of an educated mind to be able to entertain a thought without accepting it.",
    "Wisdom begins in wonder.",
    "By three methods we may learn wisdom: First, by reflection; Second, by imitation; Third by experience.",
    "The simple things are also the most extraordinary things.",
    "A wise man adapts himself to circumstances, as water shapes itself to the vessel that contains it.",
    "Patience is the companion of wisdom.",
    "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.",
    "Turn your obstacles into opportunities and your problems into possibilities.",
    "He who knows all the answers has not been asked all the questions.",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
    "A fool is known by his speech and a wise man by his silence.",
    "The art of being wise is the art of knowing what to overlook.",
    "Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.",
    "Wisdom is the reward you get for a lifetime of listening when you would have rather talked.",
    "Do not seek to follow in the footsteps of the wise. Seek what they sought.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Doubt is the beginning, not the end, of wisdom.",
    "Think before you speak. Read before you think.",
    "A wise man gets more use from his enemies than a fool from his friends.",
    "The best index to a person's character is how they treat people who can't do them any good.",
    "It's not what you look at that matters, it's what you see.",
    "No man steps in the same river twice, for it's not the same river and he's not the same man.",
    "Wisdom is the supreme part of happiness.",
    "Kindness is the ultimate form of wisdom.",
    "Peace comes from within. Do not seek it without.",
    "Knowledge is proud that he has learned so much; Wisdom is humble that he knows no more.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "The roots of education are bitter, but the fruit is sweet.",
    "He who is not courageous enough to take risks will accomplish nothing in life.",
    "It is better to keep your mouth closed and let people think you are a fool than to open it and remove all doubt.",
    "Better a witty fool than a foolish wit.",
    "Learn from the mistakes of others. You can't live long enough to make them all yourself.",
    "The measure of intelligence is the ability to change.",
    "Choose a path of continuous learning.",
    "A quiet mind is able to hear the voice of wisdom.",
    "Wisdom is the wealth of the mind.",
    "Silence is sometimes the best answer.",
    "Do not speak unless you can improve on silence.",
    "He who conquers himself is the mightiest warrior.",
    "Wisdom is oftimes nearer when we stoop than when we soar.",
    "The wisdom of life consists in the elimination of non-essentials.",
    "Knowledge speaks, but wisdom listens.",
    "Patience is a key element of wisdom.",
    "A smart person solves a problem. A wise person avoids it.",
    "To know that you do not know is the best.",
    "Wisdom is the key to unlocking inner peace.",
    "Look deep into nature, and then you will understand everything better.",
    "True wisdom is a quiet confidence.",
    "Let go of what you cannot control.",
    "Integrity is doing the right thing, even when no one is watching.",
    "A wise heart is a safe guide.",
    "The first step to wisdom is silence; the second is listening.",
    "Simplicity is the ultimate sophistication.",
    "Seek wisdom, not answers.",
    "The mind is everything. What you think you become.",
    "Wisdom is the light that illuminates the dark.",
    "Do not let the behavior of others destroy your inner peace.",
    "Knowledge is knowing a tomato is a fruit; wisdom is not putting it in a fruit salad.",
    "A wise man makes his own decisions, an ignorant man follows public opinion.",
    "Mistakes are proof that you are trying.",
    "Wisdom is the compass of life.",
    "Quiet minds are the most creative.",
    "Trust your intuition; it is the whisper of your wisdom.",
    "The wise man does not lay up his own treasures. The more he gives, the more he has.",
    "Time is the wisest counselor.",
    "Acceptance is the key to inner freedom.",
    "The highest form of wisdom is kindness.",
    "A wise man learns by the mistakes of others, a fool by his own.",
    "Wisdom is the daughter of experience.",
    "Happiness depends upon ourselves.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "True knowledge exists in knowing that you know nothing.",
    "He who has begun has half done.",
    "Wisdom is not given; we must discover it for ourselves.",
    "Listen to your silence, it holds the answers.",
    "A wise man adapts to circumstances like water to a glass.",
    "Keep your mind open and your heart peaceful.",
    "Wisdom is the ultimate treasure.",
    "Do not regret the past, learn from it.",
    "Peace of mind is the true indicator of wisdom.",
    "A wise choice is a lasting reward.",
    "The art of wisdom is knowing what to discard.",
    "Wisdom begins in silence.",
    "Live in harmony with nature.",
    "A wise leader guides with compassion.",
    "Wisdom is the ultimate shield against ignorance.",
    "Keep your feet on the ground and your mind in the stars.",
    "Be wise today, not tomorrow.",
    "Patience is the secret key to wisdom.",
    "Your inner wisdom is your best guide.",
    "Listen more, talk less.",
    "True wisdom is in understanding the balance of life."
  ]
};
